export const students = [
	{
		id: 1,
		img: 1,
		less: "Lesson",
		date: "28th April 2021",
		grade: "Creche",
		para: "For anyone validating farmer as a professional prototyping tool.",
		btn: "Enroll Now",
	},
	{
		id: 2,
		img: 2,
		less: "Lesson",
		date: "28th April 2021",
		grade: "Transition",
		para: "For anyone validating farmer as a professional prototyping tool.",
		btn: "Enroll Now",
	},
	{
		id: 3,
		img: 3,
		less: "Lesson",
		date: "28th April 2021",
		grade: "Nursery",
		para: "For anyone validating farmer as a professional prototyping tool.",
		btn: "Enroll Now",
	},
	{
		id: 4,
		img: 4,
		less: "Lesson",
		date: "28th April 2021",
		grade: "Primary",
		para: "For anyone validating farmer as a professional prototyping tool.",
		btn: "Enroll Now",
	},
	{
		id: 5,
		img: 5,
		less: "Lesson",
		date: "28th April 2021",
		grade: "Secondary",
		para: "For anyone validating farmer as a professional prototyping tool.",
		btn: "Enroll Now",
	},
];
